__include__: [
  '../dataset/steelframe_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetrv2_r50vd.yml',
]


output_dir: ./output/rtdetrv2_r50vd_6x_coco

epoches: 10

optimizer:
  type: AdamW
  params: 
    - 
      params: '^(?=.*backbone)(?!.*norm).*$'
      lr: 0.00001
    - 
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn)).*$'
      weight_decay: 0.

  lr: 0.0001
  betas: [0.9, 0.999]
  weight_decay: 0.0001

train_dataloader: 
  dataset: 
    transforms:
      policy:
        epoch: 10
  collate_fn:
    stop_epoch: 10
  total_batch_size: 16
  num_workers: 2